<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DependencyInjection\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ManolovPWS_v2.Domain\ManolovPWS_v2.Domain.csproj" />
    <ProjectReference Include="..\ManolovPWS_v2.Infrastructure\ManolovPWS_v2.Infrastructure.csproj" />
    <ProjectReference Include="..\ManolovPWS_v2.Modules.Identity\ManolovPWS_v2.Modules.Identity.csproj" />
    <ProjectReference Include="..\ManolovPWS_v2.Shared\ManolovPWS_v2.Shared.csproj" />
  </ItemGroup>

</Project>
